--- 
repository: git@github.com:HeSYINUvSBZfxqA/badonkadonk.git
application: badonkadonk

user: defn
group: defn

ruby_loader: bin/rvmrun
deploy_ruby: ree
app_ruby: ree

branches: [ master ]
branch_regex: /

chef_path:  /data/zendesk_chef

notify:
  email:
    recipients: 
    - 
  campfire:
    account:
    room:
    email:
    token:
  airbrake:
    api_key:
  flowdock:
    api_token:
    project:
    from:
      name:
      address:
    tags:
    - deploy
