--- 
repository: git@github.com:HeSYINUvSBZfxqA/badonkadonk.git
application: badonkadonk

user: defn
group: defn

ruby_loader: rvm-exec
deploy_ruby: ree
app_ruby: ree

branches: [ master ]
branch_regex: /

chef_path: /data/zendesk_chef

notify:
  nothing:
