--- 
repository: git@github.com:HeSYINUvSBZfxqA/badonkadonk.git
application: badonkadonk

user: defn
group: defn

ruby_loader: bin/rvmrun
deploy_ruby: ree
app_ruby: ree

branches: [ ]
branch_regex: ^

chef_path:  /data/zendesk_chef
